config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :appointments do
    member do
      post :toggle_status
    end

    resources :chatrooms, only: :show do
      resources :messages, only: :create
    end
  end

  resources :symptoms

  root to: "pages#home"

  get "playground" => "pages#playground"

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord

  enum status: { Pending: 'Pending', Accepted: 'Accepted', Cancelled: 'Cancelled', Closed: 'Closed' }
  validates :status, inclusion: { in: statuses.keys }

  attr_accessor :date

  belongs_to :patient, class_name: 'User'
  belongs_to :clinician, class_name: 'User'


  has_many :appointment_symptoms
  has_many :symptoms, through: :appointment_symptoms
  has_many :messages

  has_one :chatroom

  validates :appointment_date, :appointment_type, :status, :severity, presence: true

  private


end

app/models/appointment_symptom.rb
class AppointmentSymptom < ApplicationRecord
  belongs_to :appointment
  belongs_to :symptom
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  #belongs_to :patient, class_name: 'User'
  #belongs_to :clinician, class_name: 'User'
  has_many :messages
  belongs_to :appointment
end

app/models/message.rb
class Message < ApplicationRecord
  #belongs_to :appointment
  belongs_to :chatroom
  belongs_to :user

  validates :text, presence: true
  after_create_commit :broadcast_message

  private

  def broadcast_message
    broadcast_append_to "chatroom_#{chatroom.id}_messages",
                        partial: "messages/message",
                        locals: { message:self },
                        target: 'messages'
  end
end

app/models/news_item.rb
class NewsItem < ApplicationRecord
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  has_many :appointment_symptoms
  has_many :appointments, through: :appointment_symptoms

  validates :category, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments_as_clinician, class_name: 'Appointment', foreign_key: 'clinician_id'
  has_many :appointments_as_patient, class_name: 'Appointment', foreign_key: 'patient_id'
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_show_navbar, only: [:show, :new, :index]
  before_action :set_appointment, only: [:show, :edit, :update, :destroy, :confirmation, :toggle_status]
  before_action :hide_footer, only: [:new]

  def index
    if current_user.clinician
      @appointments = current_user.appointments_as_clinician.order(appointment_date: :desc)
    else
      @appointments = current_user.appointments_as_patient.order(appointment_date: :desc)
    end

    if params[:status].present?
      @appointments = @appointments.where(status: params[:status])
    end

    @appointments = @appointments.order(appointment_date: :desc)
  end

  def show
    @appointment = Appointment.find(params[:id])
    @clinician = User.find(@appointment.clinician_id)
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.patient_id = current_user.id
    @appointment.clinician_id = User.find_by(email: params[:clinician_email]).id
    @appointment.status = 'Pending'
    @appointment.appointment_date = DateTime.parse(params[:appointment][:date])
    @appointment.created_at = Time.now

    if @appointment.save!
        create_chatroom(@appointment.id)
        @clinician = @appointment.clinician
        render :show
    else
        render :new
    end
  end

  def edit
  end

  def update
    if @appointment.update(appointment_params)
      redirect_to @appointment, notice: 'Appointment changed.'
    else
      render :edit
    end
  end

  def destroy
    @appointment.destroy
    redirect_to appointments_url, notice: 'Appointment cancelled.'
  end

  def confirmation
  end

  def toggle_status
    case params[:status]
    when 'Pending'
      @appointment.update(status: 'Pending')
    when 'Accepted'
      @appointment.update(status: 'Accepted')
    when 'Closed'
      @appointment.update(status: 'Closed')
    when 'Cancelled'
      @appointment.update(status: 'Cancelled')
    end

    respond_to do |format|
      format.html { redirect_to appointments_path, notice: 'Appointment status was successfully updated.' }
      format.json { head :no_content }
    end
  end

    private

    def set_show_navbar
      @show_navbar = false
    end

    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:patient_id, :clinician_email, :date, :appointment_type, :status, :severity)
    end

    def create_chatroom(id)
      chatroom = Chatroom.new
      chatroom.appointment_id = id
      chatroom.created_at = Time.now
      chatroom.name = "room #{Chatroom.count}"
      chatroom.save!
    end

    def hide_footer
      @hide_footer = true
    end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_appointment

  def new
    @message = @appointment.messages.new
  end

  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    @message.chatroom_id = params[:chatroom_id]
    @chatroom = @message.chatroom

    # if @message.save
      if @message.save
        respond_to do |format|
          format.turbo_stream do
            render turbo_stream: turbo_stream.append(:messages, partial: "messages/message",
              locals: { message: @message })
          end
          format.html { redirect_to chatroom_path(@chatroom) }
        end
    #   ChatroomChannel.broadcast_to(
    #     @chatroom,
    #     render_to_string(partial: "message", locals: {message: @message})
    #   )
    #   @message = Message.new
    #   render "chatrooms/show", status: :ok
    else
      render "chatrooms/show", status: :unprocessable_entity
    end
  end

  private
    def set_appointment
      @appointment = Appointment.find(params[:appointment_id])
    end

    def message_params
      params.require(:message).permit(:text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :playground ]

  def home
    @show_navbar = true
  end

  def playground
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def update
    # Logic for user profile update
  end
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  def index
    @symptoms = Symptom.all
  end

  def show
    @symptom = Symptom.find(params[:id])
  end
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  def index
    # Logic for health news and health updates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/index.html.erb
<div class="">
  <div class="appointment-body">
    <div class="text-center mb-4">
      <h1 style='font-size: 30px;'>Appointments</h1>
    </div>

    <!-- Dropdown to filter appointments by status -->
    <div class="text-center mb-4">
      <%= form_with url: appointments_path, method: :get, local: true, id: 'status-filter-form', class: 'form-inline' do %>
        <%= select_tag :status, options_for_select([['All', ''], ['Pending', 'Pending'], ['Accepted', 'Accepted'], ['Closed', 'Closed']], params[:status]), class: 'form-control mr-sm-2', onchange: 'this.form.submit();' %>
      <% end %>
    </div>

    <div class="row">
      <% @appointments.each do |appointment| %>
        <div class="col-md-6 mb-5" style="margin-top: -10px; ">
          <div class="card-for-content">
            <div class="appointment-card-body">
              <%= link_to appointment_path(appointment), class: 'text-decoration-none text-dark' do %>
                <h2 class="card-title lobster-regular mb-3">
                  <strong>
                    <%= appointment.appointment_date.strftime('%A') %><br>
                    <%= appointment.appointment_date.strftime('%B %e, %Y') %>
                  </strong>
                </h2>
              <% end %>

              <% if current_user.clinician? %>
                <p class="card-text severity <%= 'severity-high' if appointment.severity == 'High' %> <%= 'severity-low' if appointment.severity == 'Low' %> roboto">
                  Severity: <%= appointment.severity %>
                </p>
              <% end %>

              <div class="d-flex align-items-center mb-2">
                <%= image_tag 'Timeapp.png', style: 'width: 30px; height: 30px; margin-right: 8px;' %>
                Time: <%= appointment.appointment_date.strftime('%I:%M %p') %>
              </div>

              <div class="d-flex align-items-center mb-2">
                <%= image_tag 'Typeapp.png', style: 'width: 30px; height: 30px; margin-right: 8px;' %>
                Type: <%= appointment.appointment_type %>
              </div>
              <div class="d-flex align-items-center mb-2">
                <%= image_tag 'Statusapp.png', style: 'width: 30px; height: 30px; margin-right: 8px;' %>
                Status: <%= appointment.status %>
              </div>
              <div class="d-flex align-items-center mb-2">
                <%= image_tag 'Clinicianapp.png', style: 'width: 30px; height: 30px; margin-right: 8px;' %>
                Clinician: <%= appointment.clinician.title %> <%= appointment.clinician.first_name %> <%= appointment.clinician.last_name %>
              </div>

              <!-- Display symptoms or default category if none -->
              <% if appointment.symptoms.any? %>
                <% appointment.symptoms.each do |symptom| %>
                  <div class="d-flex align-items-center mb-2">
                    <%= image_tag 'Category.png', style: 'width: 30px; height: 30px; margin-right: 8px;' %>
                    Category: <%= symptom.category %>
                  </div>
                <% end %>
              <% else %>
                <div class="d-flex align-items-center mb-2">
                  <%= image_tag 'Category.png', style: 'width: 30px; height: 30px; margin-right: 8px;' %>
                  Category: Muscle and Joints
                </div>
              <% end %>

              <% if current_user.clinician? %>
                <div class="appointment-button-decision">
                  <%= button_to "Close", toggle_status_appointment_path(appointment), method: :post, params: {status: "Closed"} %>
                  <%= button_to "Accept", toggle_status_appointment_path(appointment), method: :post, params: {status: "Accepted"} %>
                </div>
              <% end %>

              <% if appointment.chatroom %>
                <%= link_to 'Chat', appointment_chatroom_path(appointment, appointment.chatroom), class: 'done-button m-2' %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/appointments/new.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Playfair+Display:ital,wght@0,400..900;1,400..900&family=Playfair:ital,opsz,wght@0,5..1200,300..900;1,5..1200,300..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

<nav class="custom-navbar" style="display: flex; justify-content: space-between; align-items: center;" data-home-path="<%= root_path %>">
    <a class="btn btn-link back-button" style="margin-right: auto; display: none;">
        <i class="fas fa-arrow-left"></i>
    </a>
    <span class="navbar-brand mx-auto">Book an appointment</span>
    <a class="btn btn-link close-button" style="margin-left: auto;">
        <i class="fas fa-times"></i>
    </a>
</nav>

<%= simple_form_for @appointment, html: {class: "d-none" } do |f| %>
  <%= f.input :clinician_email do %>
    <%= text_field_tag 'clinician_email' %>
  <% end %>
  <%= f.input :date %>
  <%= f.input :appointment_type  %>
  <%= f.input :severity %>
  <%= f.button :submit %>
<% end %>

<div class="content-container">
    <div class="side-bottom-margin-container">
        <div class="appointmentbooking">
            <div id="category-list" class="form-section">
                <div>
                    <h1>How can we assist you today?</h1>
                </div>

                <div class="booking-index-headings"></div>


                <div class="category-card" data-category="muscles_and_joints">
                  <div class="image-container">
                    <%= image_tag 'muscle_joints.png', alt: 'Muscle joints', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Muscle and Joints</h3>
                    <p>Issues with your back, neck, shoulders, or other muscles and joints.</p>
                  </div>
                </div>

                <div class="category-card" data-category="contraception">
                  <div class="image-container">
                    <%= image_tag 'contraceptive.png', alt: 'contraceptive', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Contraception</h3>
                    <p>Guidance and prescriptions for contraceptive options.</p>
                  </div>
                </div>

                <div class="category-card" data-category="breathing_conditions_and_allergies">
                  <div class="image-container">
                    <%= image_tag 'breathing.png', alt: 'breathing', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Breathing Conditions & Allergies</h3>
                    <p>Management of asthma, hay fever, and other breathing-related concerns.</p>
                  </div>
                </div>

                <div class="category-card" data-category="mental_health">
                  <div class="image-container">
                    <%= image_tag 'mental_health.png', alt: 'Mental health', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Mental Health</h3>
                    <p>Advice and support for mental health issues.</p>
                  </div>
                </div>

                <div class="category-card" data-category="prescriptions">
                  <div class="image-container">
                    <%= image_tag 'medical_prescription.png', alt: 'Prescription', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Prescriptions</h3>
                    <p>Help with new or repeat prescription requests and reviews.</p>
                  </div>
                </div>

                <div class="category-card" data-category="diabetes_care">
                  <div class="image-container">
                    <%= image_tag 'diabetes_test.png', alt: 'Diabetes', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Diabetes Care</h3>
                    <p>Support and advice for diabetes and pre-diabetes management.</p>
                  </div>
                </div>

                <div class="category-card" data-category="cold_cough_flu_sore_throat_and_earaches">
                  <div class="image-container">
                    <%= image_tag 'cold_cough_flu.png', alt: 'Cold,FLu', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Cold, Cough, Flu, Sore Throat and Earaches</h3>
                    <p>Help with symptoms like cold, cough, runny nose, fever, sore throat, and ear pain.</p>
                  </div>
                </div>

                <div class="category-card" data-category="skin_issues">
                  <div class="image-container">
                    <%= image_tag 'skin_disease.png', alt: 'Cold,FLu', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Skin Problems</h3>
                    <p>Treatment for rashes, acne, eczema, infections, lumps, or moles.</p>
                  </div>
                </div>

                <div class="category-card" data-category="stomach_problems">
                  <div class="image-container">
                    <%= image_tag 'stomach.png', alt: 'Cold,FLu', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Stomach Issues</h3>
                    <p>Addressing nausea, abdominal pain, bloating, constipation, or diarrhea.</p>
                  </div>
                </div>

                <div class="category-card" data-category="urine_problems">
                  <div class="image-container">
                    <%= image_tag 'urinary.png', alt: 'Urinary', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Urinary Problems</h3>
                    <p>Trouble with urination, including pain or frequent urination.</p>
                  </div>
                </div>

                <div class="category-card" data-category="travel_health">
                  <div class="image-container">
                    <%= image_tag 'travel.png', alt: 'Travel', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Travel Health</h3>
                    <p>Travel advice and necessary vaccinations for trips abroad.</p>
                  </div>
                </div>

                <div class="category-card" data-category="admin">
                    <div class="image-container">
                        <%= image_tag 'administrator.png', alt: 'Administrative Issues', class: 'app-icons' %>
                    </div>
                    <div class="card-product-infos">
                        <h3>Administrative Issues</h3>
                        <p>For any non-clinical or administrative questions or concerns.</p>
                    </div>
                </div>

                <div class="category-card" data-category="test_results">
                  <div class="image-container">
                    <%= image_tag 'test_result.png', alt: 'Aministrative Issues', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Test Results</h3>
                    <p>Discuss your test results and plan the next steps.</p>
                  </div>
                </div>

                <div class="category-card" data-category="other">
                  <div class="image-container">
                    <%= image_tag 'others.png', alt: 'Other concerns', class: 'app-icons' %>
                  </div>
                  <div class="card-product-infos">
                    <h3>Other Concerns</h3>
                    <p>Describe your symptoms if they don't fit into the categories above.</p>
                  </div>
                </div>

              </div>
            </div>

<div id="triage-questions" class="form-section">
                <div class="booking-index-headings">
                    <h1 id="triage-title" style="padding-bottom: 12px;"></h1>
                </div>
                <div id="questions-container">
                    <div class="question-card">
                        <div class="question-buttons">
                            <button class="btn btn-primary">Yes</button>
                            <button class="btn btn-primary">No</button>
                        </div>
                    </div>
                </div>
                <button id="submit-triage" class="btn btn-primary">Submit</button>
            </div>

            <div id="reason-for-appointment" class="form-section">
                <div class="booking-index-headings">
                    <h1>Why would you like an appointment?</h1>
                </div>
                <div class="symptoms_text">
                <p>Tell us about your symptoms, condition, or reason for booking</p>
                </div>
                <textarea id="appointment-reason" maxlength="200" rows="4" class="form-control"></textarea>
                <div id="char-counter">0/500 characters</div>
                <button id="submit-reason" class="btn btn-primary">Submit</button>
            </div>

            <div id="appointment-type-list" class="form-section">
                <div class="text-center">
                    <h1>Choose your appointment type</h1>
                </div>
                <div class="">
                    <div class="appointment-type-card card p-3" data-appointment-type="in-person">
                        <i class="fas fa-user fa-2x"></i>
                        <span>In-person</span>
                    </div>

                    <div class="appointment-type-card card p-3" data-appointment-type="phone">
                        <i class="fas fa-phone fa-2x"></i>
                        <span>Phone</span>
                    </div>

                    <div class="appointment-type-card card p-3" data-appointment-type="video">
                        <i class="fas fa-video fa-2x"></i>
                        <span>Video Call</span>
                    </div>
                </div>
            </div>
              <div id="available-clinicians" class="form-section">
                  <div class="text-center">
                      <h1 style="padding-bottom: 20px;">Available Clinicians</h1>
                  </div>
                  <div id="clinicians-container" class="d-flex flex-wrap justify-content-around">
                      <!-- Clinician cards will be inserted here -->
                  </div>
              </div>


            <div id="calendar-view" class="form-section">
                <div class="text-center">
                    <h1 style="padding-bottom: 20px;">Select Date and Time</h1>
                </div>
                <div id="calendar-container" class="card">
                    <!-- Calendar will be rendered here -->
                </div>
                <div id="available-times" style="font-size:18px;" class="d-flex justify-content-center align-items-center mt-4">
                    <!-- Available times will be shown here -->
                </div>
            </div>

            <div id="booking-details" class="form-section">
                <div class="text-center">
                    <h1>Booking Details</h1>
                </div>
                <div id="details-container" class="mt-3">
                </div>
                <button id="confirm-booking" class="btn btn-primary mt-3">Confirm Booking</button>
            </div>

            <div id="appointment-pending" class="form-section appt-pending">
                <div class="text-center">
                    <h1>Appointment Request Pending</h1>
                </div>
                <br>
                <p>Thank you for requesting an appointment.</p>

                <%= image_tag 'date.png', alt: 'date_icon', class: 'confirmation-icons' %>
                <div class="confirmation-card">
                    <p>Your appointment request has been received and is currently pending approval from the clinician.</p>
                    <br>
                      <h4>Additional Information:</h4>
                      <p>Pending Approval: Your requested appointment is awaiting confirmation from the clinician. You will receive an update as soon as your appointment status changes.</p>
                      <h3>Need to make changes?</h3>
                      <p>If you need to modify or cancel your appointment request, you can do this within the section

                      <div class="text-center">
                        <%= link_to 'My Appointments', appointments_path, class:"btn btn-primary" %></p>
                      </div>


                      <footer>
                        <div class="extra-info">
                        <p>Please note that the availability of appointments may vary based on clinician schedules.</p>
                      </div>
                      </footer>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</div>

app/views/appointments/show.html.erb
<div class= "background-content">

  <div class="d-flex justify-content-around" style="padding-top: 75px;margin-bottom: 10px;">
    <div class="confirmation-icon">
      <%= image_tag 'Tick.png', alt: 'date_icon', class: 'confirmation-icons' %>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <div class= "confirmation-message">
      <h1>Booking pending </h1>
      <div>
      <p>Your appointment request has been submitted and is awaiting review by the clinician.</p>
      </div>
      <div>
      <p>An email and SMS have been sent to your registered contact details.</p>
      </div>
    </div>
  </div>

  <div class="">
    <div class= "appointment-confirmation-card d-flex">
        <% if current_user.clinician %>
          <p>I'm a clinician</p>
          <p><%= @appointment.appointment_date %></p>
        <% else %>

          <div class="profile2-image">
            <%= image_tag 'marie.jpg' %>
          </div>

          <div class="clinician-info-show">
            <h2>Dr. <%= @clinician.first_name %> <%= @clinician.last_name %></h2>
            <h5>General Practitioner</h5>

           <div class="line"></div>

            <div class="datentime">
              <p><%= @appointment.appointment_date.strftime("%B %d, %Y %I:%M %p") %></p>
            </div>
          </div>

        <% end %>
    <%# </div> %>

      <%# <div class='d-flex justify-content-around' style="
    margin-top: 25px;">
      <div>
        <%= link_to 'Done', root_path, class: 'done-button' %>
      <%# </div> %>
        <%# <% if @appointment.chatroom %>
      <%# <div> %>
        <%# <%= link_to 'Chat', appointment_chatroom_path(@appointment, @appointment.chatroom), class: 'chat-button'  %>
      <%# </div> %>
      <%# <% end %>
    <%# </div> %>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
>
  <h1>#<%= @chatroom.name %></h1>

  <%= turbo_stream_from "chatroom_#{@chatroom.id}_messages" %>
  <div id='messages' class="messages">
   <%# data-chatroom-subscription-target="messages"> %>
    <% @chatroom.messages.each do |message| %>
     <%= render "messages/message", chatroom: @chatroon, message: message %>
    <% end %>
  </div>

  <%= simple_form_for [@chatroom.appointment, @chatroom, @message],
    html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex chat-form" } do |f|
  %>
    <%= f.input :text,
      label: false,
      placeholder: "Write a message",
      wrapper_html: {class: "flex-grow-1"}
    %>
    <%= f.submit "Send", class: "btn btn-primary submit-button" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Triageline</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: false %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  </head>

  <body data-current-user-id="<%= current_user ? current_user.id : "" %>">
    <%= render "shared/navbar" %>

    <%= render "shared/flashes" %>

    <%= yield %>

    <% unless @hide_footer %>
      <%= render "shared/footerMenu" %>
    <% end %>

  </body>
</html>

app/views/messages/_form.html.erb
<!-- app/views/messages/_form.html.erb -->
<%= simple_form_for [@appointment, @chatroom, @message], url: appointment_chatroom_messages_path(@appointment, @chatroom), html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex chat-form" } do |f| %>
  <%= f.input :text, label: false, placeholder: "Write a message", wrapper_html: { class: "flex-grow-1" } %>
  <%= f.submit "Send", class: "btn btn-primary submit-button" %>
<% end %>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>" class="message-item <%= 'right' if message.user.first_name == 'Basia' %>" data-controller='message'  data-message-user-id-value='<%= message.user.id %>'>
  <% if message.user.first_name == "Basia" %>
    <!-- Display Basia Message on the Right with Avatar on the Right -->
    <div class="message-content">
      <span class="timestamp"><%= message.created_at.strftime('%a %b %-d at %l:%M %p') %></span>
      <p class="message-text"><%= message.text %></p>
    </div>
    <%= image_tag("https://res.cloudinary.com/djkohlole/image/upload/v1725412452/basia_qsrght.png", class: "avatar", alt: "Basia Avatar") %>
  <%  elsif message.user.first_name == "Marie" %>
    <!-- Display Clinician Message on the Left with Avatar on the Left -->
    <%= image_tag("https://res.cloudinary.com/djkohlole/image/upload/v1725403884/marie_vzvgyh.jpg", class: "avatar", alt: "Marie Avatar") %>
    <div class="message-content">
      <span class="timestamp"><%= message.created_at.strftime('%a %b %-d at %l:%M %p') %></span>
      <p class="message-text"><%= message.text %></p>
    </div>
  <% end %>
</div>

app/views/messages/new.html.erb
<div>

<h1>Messages</h1>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/symptoms/index.html.erb
<div>
<h1>Health History</h1>

<h2>Category</h2>

<h3>Clinician name</h3>

<h2>Summary</h2>

<%= link_to 'Back', symptoms_path %>
</div>